[pytest]
pythonpath = .
testpaths = tests
# The pytest cache folder does not work well inside OneDrive, so we turn it off.
addopts = -p no:cacheprovider
filterwarnings =
    ignore::DeprecationWarning
    ignore:.*httpx.*
