"""Private file storage, signed links and the malware-scanning hook.

Storage adapter
    LocalStorage keeps files under STORAGE_DIR, which must NOT be served by any web server.
    Keys are random ("<organisation>/<32 hex chars>"), never derived from file names, so they
    cannot be guessed. An S3/Azure/GCS adapter only needs the same five methods; the bucket
    stays private and signed links keep pointing at this API (or become native pre-signed URLs).

Signed links
    /api/v1/storage/upload/<token> and /api/v1/storage/download/<token> carry an HMAC-signed,
    short-lived token (SIGNED_URL_SECONDS) naming ONE document, ONE action and the user it was
    issued to. Knowing a document id or storage key is useless without it, and the download
    route re-checks that user's CURRENT access before sending a byte. Tokens are redacted
    from logs (see logging_setup.py).

Malware scanning
    scan_file() is the hook. The default scanner only reports NOT_SCANNED; plug a real scanner
    (ClamAV, a cloud AV API) into get_scanner(). INFECTED files are rejected and deleted.
"""
import base64
import hashlib
import hmac
import json
import os
import re
import secrets
import time
from pathlib import Path

from app.config import get_settings
from app.errors import ApiError

KEY_PATTERN = re.compile(r"^[0-9a-f-]{36}/[0-9a-f]{32}$")

# Allowed uploads: MIME type -> (allowed extensions, file signature at the start of the file).
ALLOWED_TYPES = {
    "application/pdf": ((".pdf",), (b"%PDF-",)),
    "image/png": ((".png",), (b"\x89PNG\r\n\x1a\n",)),
    "image/jpeg": ((".jpg", ".jpeg"), (b"\xff\xd8\xff",)),
}


def new_storage_key(organisation_id):
    return f"{organisation_id}/{secrets.token_hex(16)}"


def check_file_type(filename, mime_type):
    if mime_type not in ALLOWED_TYPES:
        raise ApiError(422, "VALIDATION_ERROR", "Only PDF, PNG and JPEG files can be uploaded.",
                       fields=[{"field": "mime_type", "message": "Unsupported file type."}])
    extensions, _ = ALLOWED_TYPES[mime_type]
    if not filename.lower().endswith(extensions):
        raise ApiError(422, "VALIDATION_ERROR", "The file name extension does not match the file type.",
                       fields=[{"field": "original_filename", "message": "Extension does not match mime_type."}])


def content_matches_type(first_bytes, mime_type):
    _, signatures = ALLOWED_TYPES[mime_type]
    return any(first_bytes.startswith(signature) for signature in signatures)


# ---------- Storage adapter ----------

class LocalStorage:
    def __init__(self, root: Path):
        self.root = root

    def _path(self, key):
        # The key is generated by us, but check it anyway so it can never point outside the root.
        if not KEY_PATTERN.match(key):
            raise ValueError("invalid storage key")
        return self.root / key

    def exists(self, key):
        return self._path(key).exists()

    def save(self, key, chunks, max_bytes):
        """Write the chunks to the key. Returns the size. Raises PAYLOAD_TOO_LARGE past max_bytes;
        nothing is left behind in that case."""
        path = self._path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        temporary = path.with_suffix(".part")
        size = 0
        try:
            with open(temporary, "wb") as file:
                for chunk in chunks:
                    size += len(chunk)
                    if size > max_bytes:
                        raise ApiError(413, "PAYLOAD_TOO_LARGE", "The file is larger than declared or allowed.")
                    file.write(chunk)
            os.replace(temporary, path)
        finally:
            if temporary.exists():
                temporary.unlink()
        return size

    def read_chunks(self, key, chunk_size=64 * 1024):
        with open(self._path(key), "rb") as file:
            while chunk := file.read(chunk_size):
                yield chunk

    def head(self, key, length=16):
        with open(self._path(key), "rb") as file:
            return file.read(length)

    def size_and_checksum(self, key):
        digest, size = hashlib.sha256(), 0
        for chunk in self.read_chunks(key):
            digest.update(chunk)
            size += len(chunk)
        return size, digest.hexdigest()

    def delete(self, key):
        path = self._path(key)
        if path.exists():
            path.unlink()


_storage = None


def get_storage():
    global _storage
    if _storage is None:
        _storage = LocalStorage(get_settings().storage_dir)
    return _storage


def set_storage(storage):
    """Used by tests (a temporary folder) and by future cloud adapters."""
    global _storage
    _storage = storage


# ---------- Malware scanning hook ----------

class NoScanner:
    def scan(self, storage, key):
        return "NOT_SCANNED"


_scanner = NoScanner()


def get_scanner():
    return _scanner


def set_scanner(scanner):
    global _scanner
    _scanner = scanner


# ---------- Signed tokens ----------

def _b64(data):
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode()


def _unb64(text):
    return base64.urlsafe_b64decode(text + "=" * (-len(text) % 4))


def _signature(body):
    return _b64(hmac.new(get_settings().secret_key.encode(), body.encode(), hashlib.sha256).digest())


def sign(action, document_id, user_id, scope, seconds=None):
    """Returns (token, expires_at_unix)."""
    expires = int(time.time()) + (seconds or get_settings().signed_url_seconds)
    body = _b64(json.dumps({"a": action, "d": str(document_id), "u": str(user_id), "s": scope, "e": expires,
                            "n": secrets.token_hex(4)}, separators=(",", ":")).encode())
    return f"{body}.{_signature(body)}", expires


def verify(token, action):
    """The payload of a valid, unexpired token for `action`, or a 403 with one generic message."""
    denied = ApiError(403, "INVALID_LINK", "This link is invalid or has expired. Request a new one.")
    try:
        body, signature = token.split(".", 1)
        if not hmac.compare_digest(signature, _signature(body)):
            raise denied
        payload = json.loads(_unb64(body))
    except (ValueError, TypeError) as error:
        raise denied from error
    if payload.get("a") != action or payload.get("e", 0) < time.time():
        raise denied
    return payload
